# Site settings
title: Philly Lim
description: Personal Website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Philly Lim
typing_text: Student Developer
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Software Developer
email: phillylim@ucsb.edu
twitter_username: 
github_username:  phillylim
gplus_username:
linkedin_username: phillylim

show_aboutme_card: true
about_me_title: About Me
about_me_description: 

show_skills_card: true
timeline_title: Timeline
cv_download_link: 

show_projects_card: true

show_contact_card: true
contact_title: Philly Lim
contact_description:

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
